### ISSUE TITLE
Question about derivation of disparity vertical case

### ISSUE THREAD

**Issue by Jarrome** [VCL3D/SphericalViewSynthesis#2]
Hi authors,

Excellent work. I find your paper useful and read carefully.

However, I find there's some confusing derivation in paper. Maybe I'm wrong. **(I'm only interested in the vertical case)**

Q1. In eq.2, the partial derivative of theta on y, the sin should be on the denominator instead of numerator. Maybe I miss something? A typo?

Q2. For the disparity vertical case, I find it make a different derivation comparing to the Law of sine. Shouldn't it follow the Law of sine? since the disparity is the difference of latitude.

**Comment by zuru** [comment]
Hi Jarrome,

sorry for the late reply, just found some time to be able to provide a useful answer.

Regarding **Q1**, in [`Spherical_Vertical_Disparity.pdf`](https://github.com/VCL3D/SphericalViewSynthesis/blob/material/Spherical_Vertical_Disparity.pdf) provides the full derivation for you to verify. The only difference is the use of `z` as the vertical axis (as the online figure I quickly found online was this way).

Regarding **Q2**, a quick formulation using the law of sines can be found in the [`Law_of_Sines.pdf`](https://github.com/VCL3D/SphericalViewSynthesis/blob/material/Law_of_Sines.pdf), which results into the Equation (1) of [360SD-Net: 360° Stereo Depth Estimation with Learnable Cost Volume](https://arxiv.org/pdf/1911.04460.pdf). Perhaps the ambiguity comes from considering a different radius? (i.e. the top, not bottom)



Let me know if this was helpful and suffices or please continue the discussion otherwise.

**Comment by Jarrome** [comment]
Thank you, zuru, for the detailed reply. 
I really appreciate it.

Actually, in [Spherical View Synthesis for Self-Supervised 360o Depth Estimation](url), the vertical disparity formula 
![Screen Shot 2020-06-30 at 10 15 59 AM](https://user-images.githubusercontent.com/13412144/86075538-c9c47400-baba-11ea-95b6-db3c8c06127d.png)
I find it fancy but I personally cannot relate it to the Law of sines.
In addition, I find lines of code using the formula but have no idea why the disparity looks like this.

The work is nice, I just want to better understand it.
